# Copyright (c) 2026-present K. S. Ernest (iFire) Lee & godot-onnx contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Headless inference tests (mirror Rust scene model tests). Run with:
#   godot --path sample --headless -s res://scripts/test_inference.gd
# Exit code 0 = all run tests passed; 1 = failure (missing required model or inference error).

extends Node

var _failed := false
var _log: Array[String] = []

func _ready() -> void:
	_run_tests()
	# Exit: 0 success, 1 failure
	get_tree().quit(0 if not _failed else 1)

func _fail(msg: String) -> void:
	_failed = true
	_log.append("FAIL: " + msg)
	print("FAIL: ", msg)

func _ok(msg: String) -> void:
	_log.append("OK: " + msg)
	print("OK: ", msg)

func _skip(msg: String) -> void:
	_log.append("SKIP: " + msg)
	print("SKIP: ", msg)

func _run_tests() -> void:
	# --- Required: identity and matmul (generated by CI) ---
	_test_identity()
	_test_matmul()
	# --- Optional: scene models (downloaded by download_onnx_models.py) ---
	_test_scene_model("res://models/esrgan.onnx", PackedInt64Array([1, 3, 128, 128]), "esrgan")
	_test_scene_model("res://models/pose_detection.onnx", PackedInt64Array([1, 256, 256, 3]), "pose_detection")
	_test_scene_model("res://models/pose_detection_thunder.onnx", PackedInt64Array([1, 256, 256, 3]), "pose_detection_thunder")
	_test_scene_model("res://models/mediapipe_pose_landmark_full.onnx", PackedInt64Array([1, 256, 256, 3]), "mediapipe_pose_landmark_full")

func _test_identity() -> void:
	var mod := ClassDB.instantiate("OnnxModule")
	mod.load("res://models/identity.onnx")
	if not mod.is_loaded():
		_fail("identity.onnx not loaded")
		return
	var x := PackedFloat32Array([1.0, 2.0, 3.0])
	var dim := PackedInt64Array([3])
	var input_tensor := ClassDB.class_call_static("OnnxTensor", "from_float32s", x, dim)
	var result: Array = mod.call_module("", [input_tensor])
	if result.is_empty():
		_fail("identity: no output")
		return
	var out = result[0]
	var out_data: PackedFloat32Array = out.get_data().to_float32_array()
	if out_data.size() != 3 or out_data[0] != 1.0 or out_data[1] != 2.0 or out_data[2] != 3.0:
		_fail("identity: output mismatch")
		return
	_ok("identity")

func _test_matmul() -> void:
	var mod := ClassDB.instantiate("OnnxModule")
	mod.load("res://models/matmul.onnx")
	if not mod.is_loaded():
		_fail("matmul.onnx not loaded")
		return
	var a := PackedFloat32Array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
	var b := PackedFloat32Array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
	var dim_a := PackedInt64Array([2, 3])
	var dim_b := PackedInt64Array([3, 2])
	var ta := ClassDB.class_call_static("OnnxTensor", "from_float32s", a, dim_a)
	var tb := ClassDB.class_call_static("OnnxTensor", "from_float32s", b, dim_b)
	var result: Array = mod.call_module("", [ta, tb])
	if result.is_empty():
		_fail("matmul: no output")
		return
	var out = result[0]
	var out_data: PackedFloat32Array = out.get_data().to_float32_array()
	if out_data.size() != 4:
		_fail("matmul: output size != 4")
		return
	# 2x3 @ 3x2 -> [1,2,3,4] * [1,2,3,4,5,6]^T style; ref [[22,28],[49,64]]
	var expected := [22.0, 28.0, 49.0, 64.0]
	for i in 4:
		if abs(out_data[i] - expected[i]) > 1e-4:
			_fail("matmul: output value mismatch at %d" % i)
			return
	_ok("matmul")

func _test_scene_model(path: String, dim: PackedInt64Array, name: String) -> void:
	if not ResourceLoader.exists(path):
		_skip("%s (file not found)" % name)
		return
	var mod := ClassDB.instantiate("OnnxModule")
	mod.load(path)
	if not mod.is_loaded():
		_skip("%s (load failed)" % name)
		return
	var n := 1
	for i in dim.size():
		n *= int(dim[i])
	var float_data := PackedFloat32Array()
	float_data.resize(n)
	# Leave zeros
	var input_tensor := ClassDB.class_call_static("OnnxTensor", "from_float32s", float_data, dim)
	var result: Array = mod.call_module("", [input_tensor])
	if result.is_empty():
		_skip("%s: no output (model may expect different input type)" % name)
		return
	_ok("%s (outputs: %d)" % [name, result.size()])
